name: Bot Vuelos Semanal
on:
  schedule:
    # Minuto 0, Hora 3, Cualquier día mes, Cualquier mes, Día semana 2 (Martes)
    - cron: '0 3 * * 2'
  workflow_dispatch: # Botón manual para pruebas

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar librerías
        run: pip install requests
      - name: Ejecutar Alerta
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alerta.py
